import {
  Activity,
  Frame,
  BarChart3,
  Boxes,
  GitBranch,
  Network,
  Package,
  Plus,
  Rocket,
  Workflow,
  Box,
  Search,
  Play,
  Trash2,
  Power,
  Sun,
  Moon,
  ChevronRight,
  CircleDot,
  Undo2,
  Redo2,
  Pause,
  SkipBack,
  SkipForward,
  Download,
  Upload,
  Volume2,
  VolumeX,
  Wand2,
  History,
  GitFork,
  Maximize2,
  Minimize2,
  PanelLeftClose,
  PanelLeftOpen,
  SunMoon,
  Cpu,
  Gauge,
  Settings,
  Users,
  User,
  UserPlus,
  KeyRound,
  KeySquare,
  LogOut,
  Ban,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  workflow: Workflow,
  "git-branch": GitBranch,
  activity: Activity,
  "bar-chart": BarChart3,
  boxes: Boxes,
  package: Package,
  network: Network,
  plus: Plus,
  rocket: Rocket,
  search: Search,
  play: Play,
  trash: Trash2,
  power: Power,
  sun: Sun,
  moon: Moon,
  cpu: Cpu,
  gauge: Gauge,
  settings: Settings,
  users: Users,
  user: User,
  "user-plus": UserPlus,
  "key-round": KeyRound,
  "key-square": KeySquare,
  "log-out": LogOut,
  ban: Ban,
  "shield-check": ShieldCheck,
};

/** Render a lucide icon by its kebab name (from menu/command manifests). */
export function Icon({ name, size = 16, className }: { name?: string; size?: number; className?: string }) {
  const C = (name && MAP[name]) || Box;
  return <C size={size} className={className} />;
}

export {
  Frame, ChevronRight, CircleDot, Sun, Moon, SunMoon, Search, Play, Plus, Rocket, Power, Trash2, Undo2, Redo2, Pause, SkipBack, SkipForward, Download, Upload, Volume2, VolumeX, Wand2, History, GitFork, Maximize2, Minimize2, PanelLeftClose, PanelLeftOpen, Cpu, Gauge, Settings, User, LogOut };
