/** @pattern-js/mod-ai — shared op helpers. */

import type { OpContext } from "@pattern-js/core";
import type { NeutralMessage, Usage } from "@pattern-js/mod-agents";
import { modelRefSchema } from "@pattern-js/mod-agents";
import type { AiProviderService } from "../provider.js";
import { AI_PROVIDER_SERVICE, blobStore } from "../well-known.js";
import { toModelMessages } from "../messages.js";
import type { MediaRef } from "../types.js";
import type { LanguageModel, ModelMessage } from "../sdk.js";

export async function maybe<T>(ctx: OpContext, port: string): Promise<T | undefined> {
  return ctx.input.has(port) ? ((await ctx.input.value(port)) as T) : undefined;
}

export function providerService(ctx: OpContext): AiProviderService {
  const svc = ctx.services[AI_PROVIDER_SERVICE] as AiProviderService | undefined;
  if (!svc) throw new Error("mod-ai: provider service missing — install @pattern-js/mod-ai.");
  return svc;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function mapUsage(u: any): Usage | undefined {
  if (!u) return undefined;
  return { inputTokens: u.inputTokens, outputTokens: u.outputTokens, totalTokens: u.totalTokens };
}

/** Store generated bytes in the blob store and return a MediaRef. */
export async function putMedia(
  ctx: OpContext,
  bytes: Uint8Array,
  mime: string,
  kind: MediaRef["kind"],
): Promise<MediaRef> {
  const meta = await blobStore(ctx).blobs.put(bytes, { mime });
  return { blobId: meta.id, mime: meta.mime, kind };
}

/** Resolve the bytes behind a MediaRef (for transcription input). */
export async function mediaBytes(ctx: OpContext, ref: MediaRef): Promise<Uint8Array> {
  const hit = await blobStore(ctx).blobs.get(ref.blobId);
  if (!hit) throw new Error(`mod-ai: no blob "${ref.blobId}".`);
  return new Uint8Array(await new Response(hit.stream).arrayBuffer());
}

/** Build the (model, system, messages) trio every text-ish op needs. */
export async function textInput(ctx: OpContext): Promise<{
  model: LanguageModel;
  system: string | undefined;
  messages: ModelMessage[];
}> {
  const [modelRef, prompt, messagesIn, system] = await Promise.all([
    ctx.input.value("model"),
    maybe<string>(ctx, "prompt"),
    maybe<NeutralMessage[]>(ctx, "messages"),
    maybe<string>(ctx, "system"),
  ]);
  const model = await providerService(ctx).languageModel(modelRefSchema.parse(modelRef), ctx);
  const neutral: NeutralMessage[] = messagesIn ?? (typeof prompt === "string" ? [{ role: "user", content: prompt }] : []);
  return { model, system, messages: await toModelMessages(neutral, ctx) };
}
